version: '3.7'

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    user: 1000:1000
    volumes:
    - .:/var/www/app
    depends_on:
      - database
    networks:
      - contacts
  database:
   image: mariadb:10.5.9
   environment:
     MYSQL_ROOT_PASSWORD: mysql
     MYSQL_DATABASE: contacts
     MYSQL_USER: contacts
     MYSQL_PASSWORD: contacts
   networks:
     - contacts
  web:
    image: nginx:1.19
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates:ro
      - ./:/var/www/app
    ports:
      - 80:80
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    depends_on:
      - app
    networks:
      - contacts
  encore:
    image: node:15-alpine
    volumes:
    - .:/app
    working_dir: /app
    depends_on:
      - app
    command: sh -c "yarn install && yarn encore production"

networks:
  contacts:
    driver: bridge